  version: 0.0
  os: linux
  files:
    - source: target/thymeleaf-vue-spring-boot-0.1.0.jar
      destination: /home/ec2-user/
  hooks:
    #BeforeInstall:
    #  - location: scripts/install_dependencies.sh
    #    timeout: 300
    #    runas: root
    #AfterInstall:
    #  - location: scripts/change_permissions.sh
    #    timeout: 300
    #    runas: root
    ApplicationStart:
      - location: scripts/start_server.sh
      #- location: scripts-codedeploy/create_test_db.sh
        timeout: 300
        runas: root
    ApplicationStop:
      - location: scripts/stop_server.sh
        timeout: 300
        runas: root