image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean install # -B batch mode makes Maven less verbose
          #- curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"target/demo-0.0.1-SNAPSHOT.jar"
          #- mv target/thymeleaf-vue-spring-boot-0.1.0.war target/ROOT.war
          #- ls target
        artifacts:
          - target/thymeleaf-vue-spring-boot-0.1.0.jar
          # declare artifact to be included codeDeploy
         # - target/ROOT.war
    - step:
        # set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_DEFAULT_REGION as environment variables
        name: Deploy to AWS
        trigger: manual
        deployment: test   # set to test, staging or production
        # trigger: manual  # uncomment to have a manual step
        image: atlassian/pipelines-awscli
        script:
        - aws deploy push --application-name $AWS_APPLICATION_NAME --s3-location s3://$S3_BUCKET/$S3_KEY --ignore-hidden-files
        - aws deploy create-deployment --application-name $AWS_APPLICATION_NAME --s3-location bucket=$S3_BUCKET,key=$S3_KEY,bundleType=zip --deployment-group-name $DEPLOYMENT_GROUP_NAME --ignore-application-stop-failures