package com.laurelautolease.laurelAutoLease;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Lal")
public class Lal {
        String id;
        String email;
        String about;
        String twitterLink;
        String linkedinLink;
        String facebookLink;
        String telephoneNumber;
        String logoLink;
        String footerLogoLink;

        public Lal(Boolean populate) {
            this.id="0";
            this.footerLogoLink="LaurelBold.png";
            this.about = "Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.";
            this.twitterLink = "https://twitter.com/LaurelAutolease";
            this.linkedinLink = "#";
            this.facebookLink = "https://www.facebook.com/LaurelAutolease/";
            this.telephoneNumber = "0141 463 4796";
            this.logoLink = "LaurelBoldWhite.png";
            this.email="info@laurelautolease.com";
        }

        public Lal() {
            this.id="0";
            this.footerLogoLink="";
            this.about = "";
            this.twitterLink = "";
            this.linkedinLink = "";
            this.facebookLink = "";
            this.telephoneNumber = "";
            this.logoLink = "";
            this.email="";
        }

/*    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey*/
@DynamoDBHashKey(attributeName="Id")
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getEmail() {
            return email;
        }

        public void setEmail(String email) {
            this.email = email;
        }

    @DynamoDBAttribute
        public String getAbout() {
            return about;
        }

        public void setAbout(String about) {
            this.about = about;
        }

    @DynamoDBAttribute
        public String getTwitterLink() {
            return twitterLink;
        }

        public void setTwitterLink(String twitterLink) {
            this.twitterLink = twitterLink;
        }

    @DynamoDBAttribute
        public String getLinkedinLink() {
            return linkedinLink;
        }

        public void setLinkedinLink(String linkedinLink) {
            this.linkedinLink = linkedinLink;
        }

    @DynamoDBAttribute
        public String getFacebookLink() {
            return facebookLink;
        }

        public void setFacebookLink(String facebookLink) {
            this.facebookLink = facebookLink;
        }

    @DynamoDBAttribute
        public String getTelephoneNumber() {
            return telephoneNumber;
        }

        public void setTelephoneNumber(String telephoneNumber) {
            this.telephoneNumber = telephoneNumber;
        }

    @DynamoDBAttribute
        public String getLogoLink() {
            return logoLink;
        }

        public void setLogoLink(String logoLink) {
            this.logoLink = logoLink;
        }

    @DynamoDBAttribute
    public String getFooterLogoLink() {
        return footerLogoLink;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setFooterLogoLink(String footerLogoLink) {
        this.footerLogoLink = footerLogoLink;
    }
}